# Generated by Django 4.2.28 on 2026-02-11 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('service_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, verbose_name='Surname')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=10)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('lga_of_origin', models.CharField(max_length=50, verbose_name='LGA')),
                ('date_of_enlistment', models.DateField()),
                ('rank', models.CharField(choices=[('PTE', 'Private'), ('LCPL', 'Lance Corporal'), ('CPL', 'Corporal'), ('SGT', 'Sergeant'), ('SSGT', 'Staff Sergeant'), ('WO', 'Warrant Officer'), ('MWO', 'Master Warrant Officer'), ('AWO', 'Army Warrant Officer'), ('2LT', 'Second Lieutenant'), ('LT', 'Lieutenant'), ('CAPT', 'Captain'), ('MAJ', 'Major'), ('LTCOL', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BRIG', 'Brigadier General'), ('MAJGEN', 'Major General'), ('LTGEN', 'Lieutenant General'), ('GEN', 'General')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('principal_officer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_section', to='personnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_qualification', models.CharField(help_text='e.g. B.Sc, MSc, SSCE', max_length=100)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='personnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='CareerProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rank', models.CharField(choices=[('PTE', 'Private'), ('LCPL', 'Lance Corporal'), ('CPL', 'Corporal'), ('SGT', 'Sergeant'), ('SSGT', 'Staff Sergeant'), ('WO', 'Warrant Officer'), ('MWO', 'Master Warrant Officer'), ('AWO', 'Army Warrant Officer'), ('2LT', 'Second Lieutenant'), ('LT', 'Lieutenant'), ('CAPT', 'Captain'), ('MAJ', 'Major'), ('LTCOL', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BRIG', 'Brigadier General'), ('MAJGEN', 'Major General'), ('LTGEN', 'Lieutenant General'), ('GEN', 'General')], max_length=10)),
                ('date_of_last_promotion', models.DateField(blank=True, null=True)),
                ('date_of_last_transfer', models.DateField(blank=True, null=True)),
                ('command_last_served', models.CharField(help_text='Previous Command', max_length=100)),
                ('years_in_service', models.IntegerField(default=0)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_history', to='personnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(help_text='e.g., SDS, Escort Commander', max_length=100)),
                ('sub_unit', models.CharField(blank=True, help_text='e.g., Transport, Govt House Unit', max_length=100)),
                ('date_of_posting', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='personnel.personnel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.section')),
            ],
        ),
        migrations.CreateModel(
            name='GuardDutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=5)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_duties', to='personnel.personnel')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('personnel', 'date', 'shift_type')},
            },
        ),
    ]
