# Generated by Django 4.2.28 on 2026-02-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerprogression',
            name='current_rank',
            field=models.CharField(choices=[('DII', 'DII'), ('DI', 'DI'), ('CD', 'CD'), ('ASO', 'ASO'), ('SO', 'SO'), ('SIOII', 'SIOII'), ('SIOI', 'SIOI'), ('SSIO', 'SSIO'), ('PSIO', 'PSIO'), ('CSIO', 'CSIO'), ('ADIS', 'ADIS'), ('DDIS', 'DDIS'), ('DIS', 'DIS'), ('ADG', 'ADG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.CharField(choices=[('DII', 'DII'), ('DI', 'DI'), ('CD', 'CD'), ('ASO', 'ASO'), ('SO', 'SO'), ('SIOII', 'SIOII'), ('SIOI', 'SIOI'), ('SSIO', 'SSIO'), ('PSIO', 'PSIO'), ('CSIO', 'CSIO'), ('ADIS', 'ADIS'), ('DDIS', 'DDIS'), ('DIS', 'DIS'), ('ADG', 'ADG')], max_length=10),
        ),
    ]
